# Generated by Django 4.0.3 on 2022-09-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0002_product_category_product_price_product_prod_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='', upload_to='ekart/images'),
        ),
    ]
